name: Compile and deploy to heroku

on:
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haxe environment
        # You may pin to the exact commit or the version.
        # uses: krdlab/setup-haxe@aab4595a86d3a14ec1b51b9dabad6b6e7810313e
        uses: krdlab/setup-haxe@v1.1.4
        with:
          # Version Spec of the version to use. Example: 3.4.7
          haxe-version: 4.1.4
      - name: Install haxe lib
        continue-on-error: true
        run: |
          haxelib git twitch-auth https://github.com/Sacramentix/hx-twitch-auth.git --always
          haxelib git twitch-api-call https://github.com/Sacramentix/hx-twitch-api-call.git --always
          haxelib git d-fischer-logger https://github.com/Sacramentix/hx-d-fischer-logger.git --always
          haxelib git d-fischer-shared-utils https://github.com/Sacramentix/hx-d-fischer-shared-utils.git --always
          haxelib git d-fischer-typed-event-emitter https://github.com/Sacramentix/hx-d-fischer-typed-event-emitter.git --always
          haxelib git d-fischer-connection https://github.com/Sacramentix/hx-d-fischer-connection.git --always
          haxelib git ws https://github.com/Sacramentix/hx-ws.git --always
          haxelib install uuid --always
          haxelib install tink_json --always
      - name: Install twitch lib
        continue-on-error: true
        run: |
          haxelib git twitch https://github.com/Sacramentix/hx-twitch.git --always
      - name: Install ircv3 lib
        continue-on-error: true
        run: |
          haxelib git ircv3 https://github.com/Sacramentix/hx-ircv3.git --always
      - name: Install twitch chat client lib
        continue-on-error: true
        run: |
          haxelib git twitch-chat-client https://github.com/Sacramentix/hx-twitch-chat-client.git --always   
      - name: Build backend
        run: |
          haxe node.hxml
      - name: Setup Quasar
          # You may pin to the exact commit or the version.
          # uses: joshstrange/setup-quasar@35f247113004c44d5ce8a3e9a4133b78f9383404
        uses: joshstrange/setup-quasar@1.0.0
      - name: Install frontend lib
        run: |
          cd front-quasar/wiki-adventure-quasar; npm i;
      - name: Build frontend
        run: |
           quasar build
      - name: Deploy to heroku
        uses: Sacramentix/heroku-deploy@30f0b7e30306900d74c1d7fd5414e1f8421652ba
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wiki-adventure-io"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "bin"
        env:
          HD_TWITCH_BOT_USERNAME: ${{secrets.TWITCH_BOT_USERNAME}}
          HD_TWITCH_BOT_PASSWORD: ${{secrets.TWITCH_BOT_PASSWORD}}
          HD_TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
          HD_TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}
          HD_TWITCH_REDIRECT_URL: ${{secrets.TWITCH_REDIRECT_URL}}
