name: Deploy to dev 

on:
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
      TWITCH_BOT_USERNAME: ${{secrets.TWITCH_BOT_USERNAME}}
      TWITCH_BOT_PASSWORD: ${{secrets.TWITCH_BOT_PASSWORD}}
      TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
      TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}
      TWITCH_REDIRECT_URL: ${{secrets.TWITCH_REDIRECT_URL}}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Tell the player of incoming update
        run: curl -u ":${{secrets.ADMIN_SECRET}}" https://wiki-adventure-dev.herokuapp.com/api/announce --data "New update is coming your party will be interrupted in few minute."
      - continue-on-error: true
        run: |
          git config --global user.email 'benji.u1225u@gmail.com'
          git config --global user.name 'Sacramentix'
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0
      - name: Install lix
        run: |
          cd back
          npm i
      - name: Build backend
        run: |
          cd back
          npx haxe node.hxml
      - name: Install frontend lib
        run: |
          cd front
          npm i
      - name: Build frontend
        run: |
          cd front
          npm i @quasar/cli
          npx quasar build -m pwa -d
      - name: Deploy to heroku
        uses: Sacramentix/heroku-deploy@30f0b7e30306900d74c1d7fd5414e1f8421652ba
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "wiki-adventure-dev"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "bin"
        env:
          HD_ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
          HD_TWITCH_BOT_USERNAME: ${{secrets.TWITCH_BOT_USERNAME}}
          HD_TWITCH_BOT_PASSWORD: ${{secrets.TWITCH_BOT_PASSWORD}}
          HD_TWITCH_CLIENT_ID: ${{secrets.TWITCH_CLIENT_ID}}
          HD_TWITCH_CLIENT_SECRET: ${{secrets.TWITCH_CLIENT_SECRET}}
          HD_TWITCH_REDIRECT_URL: ${{secrets.TWITCH_REDIRECT_URL}}
